export const restaurantsData = [
  {
    id: "142670",
    name: "Shah Ghouse Hotel & Restaurant",
    cloudinaryImageId: "bk26jkkqpg55veii0aj9",
    locality: "Santh Nirankari Satsang Bhavan",
    areaName: "Banjara Hills",
    costForTwo: "₹350 for two",
    avgRating: 4.2,
    parentId: "19271",
    avgRatingString: "4.2",
    totalRatingsString: "10K+",
    cusinies: ["Biryani", "Chinese", "Tandoor", "Mughlai", "North Indian"],
  },
  {
    id: "4138",
    name: "Grand Hotel",
    cloudinaryImageId: "g1arzw6qd7g9affkmgzk",
    locality: "Banjara Hills",
    areaName: "Abids",
    costForTwo: "₹300 for two",
    cusinies: ["Biryani", "Chinese", "Tandoor", "Haleem"],
  },
  {
    id: "3324",
    name: "Srikanya",
    cloudinaryImageId: "tw4ytwle8yommmgdy4b0",
    locality: "Kondapur",
    areaName: "Punjagutta",
    costForTwo: "₹250 for two",
    cusinies: ["Andhra", "Seafood"],
  },
  {
    id: "262087",
    name: "Imperial Multi-Cusine Restaurant",
    cloudinaryImageId: "rqlwvsmzcfxbg9u6ajgm",
    locality: "Banjara Hills",
    areaName: "Redhills",
    costForTwo: "₹400 for two",
    cusinies: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
  },
  {
    id: "376914",
    name: "Theobroma",
    cloudinaryImageId: "63dd75492c47fcec191132b8eb299ea5",
    locality: "Central Zone",
    areaName: "Somajiguda & Khairtabad",
    costForTwo: "₹400 for two",
    cusinies: ["Desserts"],
  },

  {
    id: "27739",
    name: "Cafe Niloufer Classic",
    cloudinaryImageId: "1171b83d63d7c203e5f1c3e16980cd89",
    locality: "Oshiwara",
    areaName: "Red Hills",
    costForTwo: "₹150 for two",
    cusinies: ["Sweets", "Desserts", "Snacks", "Beverages"],
  },
  {
    id: "359256",
    name: "NIC Ice Creams",
    cloudinaryImageId: "85825a6d74b1059a63a9b688de9f67ce",
    locality: "Secunderabad",
    areaName: "Bhoiguda",
    costForTwo: "₹120 for two",
    cusinies: ["Snacks", "Bakery", "Desserts", "Beverages"],
  },
  {

  }
];
