export const restaurants = [
  {
    id: "142670",
    name: "Shah Ghouse Hotel & Restaurant",
    cloudinaryImageId: "bk26jkkqpg55veii0aj9",
    locality: "Santh Nirankari Satsang Bhavan",
    areaName: "Banjara Hills",
    costForTwo: "₹350 for two",
    cuisines: ["Biryani", "Chinese", "Tandoor", "Mughlai", "North Indian"],
    menuCards: [
      {
        id: "90895506",
        name: "Grill Chicken",
        category: "Starters & Platters",
        description: "Served With Green Chutney.",
        imageId: "pmzo5ivmtv4lmpimklk6",
        defaultPrice: 25000,
      },
      {
        id: "92938018",
        name: "Tandoori Chicken {full Bird}",
        category: "Starters & Platters",
        description: "Served With Green Chutney.",
        imageId: "gwur0ij2zfwgwgc8zwxl",
        inStock: 1,
        price: 40000,
      },
      {
        id: "92938019",
        name: "Tandoori Chicken {half Bird}",
        category: "Starters & Platters",
        imageId: "ohv9dhsoqav45ac8satw",
        inStock: 1,
        price: 23000,
      },
    ],
  },
  {
    id: "4138",
    name: "Grand Hotel",
    cloudinaryImageId: "g1arzw6qd7g9affkmgzk",
    locality: "Banjara Hills",
    areaName: "Abids",
    costForTwo: "₹300 for two",
    cuisines: ["Biryani", "Chinese", "Tandoor", "Haleem"],
    menuCards: [
      {
        id: "11358461",
        name: "Single Chicken Biryani",
        category: "Rice And Biryanis",
        imageId: "qtda4lwfmlwweg3ecibu",
        inStock: 1,
        price: 13000,
      },
      {
        id: "11150881",
        name: "Veg Biryani",
        category: "Rice And Biryanis",
        imageId: "z6gl3zz2idgkxti6ow4l",
        inStock: 1,
        isVeg: 1,
        price: 12000,
      },
      {
        id: "9432227",
        name: "Chicken 65",
        category: "Starters ",
        imageId: "gpwknlfjkt1zsz70uyk4",
        inStock: 1,
        price: 20000,
      },
      {
        id: "9432231",
        name: "Chicken Lollipop",
        category: "Starters ",
        imageId: "xqzzguxxotdnljvdbgmp",
        inStock: 1,
        price: 22000,
      },
      {
        id: "9432230",
        name: "Chicken Drumstick",
        category: "Starters ",
        imageId: "ddhtdixvqm5inktrlkyy",
        inStock: 1,
        price: 22000,
      },
      {
        id: "74955657",
        name: "Andhra Karampudi Prawns",
        category: "Starters ",
        description:
          "Without coating Prawns saute with karampudi powder to make better spicy.......",
        imageId: "r68gf2q4pvp5phkzliev",
        inStock: 1,
        price: 25000,
      },
      {
        id: "9432225",
        name: "Chicken Tikka",
        category: "Starters ",
        imageId: "eml76ln1tpfurpmnpzm1",
        inStock: 1,
        price: 22000,
      },
      {
        id: "9432220",
        name: "Grilled Chicken (full)",
        category: "Starters ",
        imageId: "ebllt7fktxk8fjobn0te",
        inStock: 1,
        price: 30000,
      },
      {
        id: "9432226",
        name: "Murgh Malai Kebab",
        category: "Starters ",
        imageId: "spc0pc15qzyb67sfsjsc",
        inStock: 1,
        price: 22000,
      },
    ],
  },
  {
    id: "262087",
    name: "Imperial Multi-Cusine Restaurant",
    cloudinaryImageId: "rqlwvsmzcfxbg9u6ajgm",
    locality: "Banjara Hills",
    areaName: "Redhills",
    costForTwo: "₹400 for two",
    cuisines: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
    menuCards: [
      {
        id: "70778003",
        name: "Mixed Platter",
        category: "Platters",
        description:
          "(Malai Kabab, Tangdi, Chicken Tikka, Angara Kabab, Talawa Mutton, Prawns And Fish)",
        imageId: "ctpq02ydqqg51ymesfth",
      },
      {
        id: "51946704",
        name: "Paneer 65",
        category: "Starters",
        imageId: "i9samjc4smdsjhu7sxvw",
        defaultPrice: 16900,
      },
      {
        id: "9432225",
        name: "Chicken Tikka",
        category: "Starters ",
        imageId: "eml76ln1tpfurpmnpzm1",
        inStock: 1,
        price: 22000,
      },
    ],
  },
  {
    id: "359812",
    name: "Grameen Kulfi",
    cloudinaryImageId: "seocllwq69kt3virhyj0",
    locality: "Secunderabad",
    areaName: "Bhoiguda",
    costForTwo: "₹120 for two",
    cuisines: ["Ice Cream", "Desserts"],
    menuCards: [
      {
        id: "90895506",
        name: "Grill Chicken",
        category: "Starters & Platters",
        description: "Served With Green Chutney.",
        imageId: "pmzo5ivmtv4lmpimklk6",
        defaultPrice: 25000,
      },
      {
        id: "92938018",
        name: "Tandoori Chicken {full Bird}",
        category: "Starters & Platters",
        description: "Served With Green Chutney.",
        imageId: "gwur0ij2zfwgwgc8zwxl",
        inStock: 1,
        price: 40000,
      },
      {
        id: "9432225",
        name: "Chicken Tikka",
        category: "Starters ",
        imageId: "eml76ln1tpfurpmnpzm1",
        inStock: 1,
        price: 22000,
      },
      {
        id: "9432226",
        name: "Murgh Malai Kebab",
        category: "Starters ",
        imageId: "spc0pc15qzyb67sfsjsc",
        inStock: 1,
        price: 22000,
      },
    ],
  },
  {
    id: "74979",
    name: "Ohri's Cake Nation",
    cloudinaryImageId: "5a7d6bc7b47b77e0d517e8608e740da9",
    locality: "Basheerbagh",
    areaName: "Basheerbagh",
    costForTwo: "₹450 for two",
    cuisines: ["Bakery", "Desserts", "Beverages"],
  },
  {
    id: "359256",
    name: "NIC Ice Creams",
    cloudinaryImageId: "85825a6d74b1059a63a9b688de9f67ce",
    locality: "Secunderabad",
    areaName: "Bhoiguda",
    costForTwo: "₹120 for two",
    cuisines: ["Ice Cream", "Desserts"],
    menuCards: [
      {
        id: "66752472",
        name: "Chocochips Ice Cream 500ml",
        category: "500 Ml Ice Creams",
        description:
          "Melt in mouth chocolate chips in every spoon. Truly, a decadent ice cream experience. [Energy: 204 kcal, Allergen: milk,nuts, Carbohydrates: 24g]",
        imageId: "2791b4e0a62bbca96c37780572a27045",
        price: 25424,
      },
      {
        id: "66752480",
        name: "Tender Coconut Ice Cream 500ml",
        category: "500 Ml Ice Creams",
        price: 25424,
      },
    ],
  },
  {
    id: "112288",
    name: "Kwality Walls Dessert and Ice Cream Shop",
    cloudinaryImageId: "ihhogbpgpudzvikwmzjg",
    locality: "THE LOP STOP ICE CREAM",
    areaName: "Basheer Bagh",
    costForTwo: "₹100 for two",
    cuisines: ["Desserts", "Ice Cream"],
    menuCards: [
      {
        id: "123847166",
        name: "Slow Churn Mango Ice Cream 500 ML",
        category: "Slow Churn Artisanal Ice Cream (Exciting New Flavors)",
        price: 37500,
      },
      {
        id: "123847164",
        name: "Slow Churn Guava Ice Cream 500 ML",
        category: "Slow Churn Artisanal Ice Cream (Exciting New Flavors)",
        price: 37500,
      },
    ],
  },
  {
    id: "3324",
    name: "Srikanya",
    cloudinaryImageId: "tw4ytwle8yommmgdy4b0",
    locality: "Kondapur",
    areaName: "Punjagutta",
    costForTwo: "₹250 for two",
    cusinies: ["Andhra", "Seafood"],
    menuCards: [
      {
        id: "565171",
        name: "Sri Kanya Chicken Biryani Fry Piece - Cbf",
        category: "Non-veg Biryani",
        imageId: "buchh1zmqz5ag5q13mmo",
        price: 31000,
      },
      {
        id: "565172",
        name: "Chicken Dum Biryani",
        category: "Non-veg Biryani",
        imageId: "lpgp50r2bjex7pqp94vz",
        price: 30000,
      },
    ],
  },

  {
    id: "395225",
    name: "McDonald's Gourmet Burger Collection",
    cloudinaryImageId: "d3eewg9jbq6a94fzzc8k",
    locality: "Alto Trade Center",
    areaName: "Himayatnagar",
    costForTwo: "₹600 for two",
    cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
    menuCards: [
      {
        id: "72258449",
        name: "Vanilla Chocolate Muffin",
        category: "Cakes, Brownies & Croissants",
        description:
          "Sweet, soft, and fluffy vanilla flavoured chocolate chip muffins are perfect accompaniment with hot coffee!",
        imageId: "56ecb9e43f657ee8f239cc22f7831b83",
        inStock: 1,
        price: 12857,
      },
      {
        id: "72258451",
        name: "Chocolate Chip Muffin",
        category: "Cakes, Brownies & Croissants",
        description:
          "Soft, fluffy, and bursting with chocolate chips with muffin is loaded with chocolate!",
        imageId: "6c748c0b21f4a99593d1040021500430",
        inStock: 1,
        isVeg: 1,
        price: 14190,
      },
    ],
  },
  {
    id: "376914",
    name: "Theobroma",
    cloudinaryImageId: "63dd75492c47fcec191132b8eb299ea5",
    locality: "Central Zone",
    areaName: "Somajiguda & Khairtabad",
    costForTwo: "₹400 for two",
    cusinies: ["Desserts"],
    menuCards: [
      {
        id: "100165432",
        name: "Eggless Chocolate Orange Mousse Cake [1/2kg]",
        category: "Cakes",
        description:
          "Creamy dark chocolate mousse & our house-made fresh orange marmalade layered on moist dark chocolate sponge.",
        imageId: "803e06234d94fb5297307a29e276136a",
        price: 62500,
      },
    ],
  },
  {
    id: "35542",
    name: "Sweet Truth - Cake and Desserts",
    cloudinaryImageId: "81cf6bfe2760a45a0caf2e28716ca4d7",
    locality: "Chikadpally",
    areaName: "Himayatnagar",
    costForTwo: "₹450 for two",
    cuisines: ["Snacks", "Bakery", "Desserts", "Beverages"],
    menuCards: [
      {
        id: "133661606",
        name: "Macarons (Box of 5)",
        category: "Women's Day Specials",
        description:
          "Assortment of 5 flavours of Macarons (Chocolate, Hazelnut Salted Caramel, Alphonso Mango, Matcha Pistachio, Oreo)",
        imageId: "d9eb2bb2ac9454a154e5819b72da0fd3",
        inStock: 1,
        price: 29900,
      },
      {
        id: "135859273",
        name: "Mango Cheesecake (500 gm) (Eggless)",
        category: "Women's Day Specials",
        description:
          "Our topseller mango cheesecake slice was just not enough which is why, here's a cake. Creamy, delicious and made with actual mangoes, we are sure this mango cheesecake will not dissapoint you with it's delectable taste.",
        imageId: "7d32c2f70493a580068350ae5346d18d",
        price: 79900,
      },
    ],
  },
  {
    id: "27739",
    name: "Cafe Niloufer Classic",
    cloudinaryImageId: "1171b83d63d7c203e5f1c3e16980cd89",
    locality: "Oshiwara",
    areaName: "Red Hills",
    costForTwo: "₹150 for two",
    cusinies: ["Sweets", "Desserts", "Snacks", "Beverages"],
    menuCards: [
      {
        id: "81307682",
        name: "Black Forest Cake",
        category: "Regular Cakes",
        description: "Serves 0 | Subject To Available Garnish. ",
        imageId: "33d1ebd63d3aec63efce7d8218de73ef",
        defaultPrice: 45000,
      },
      {
        id: "115546954",
        name: "Tres Leches Cake ",
        category: "Eggless Cakes",
        description: "Serves 0",
        imageId: "38fcacb11b25c8af36d5be5c93f29de1",
        defaultPrice: 135000,
      },
    ],
  },
  {
    id: "373904",
    name: "Baskin Robbins",
    cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
    locality: "BHARGAVI ENCLAVE",
    areaName: "Nallakunta & Vidyanagar",
    costForTwo: "₹250 for two",
    cuisines: ["Desserts", "Ice Cream"],
    menuCards: [
      {
        id: "72241029",
        name: "Mississippi Mud Ice Cream",
        category: "Chocolate Ice Creams",
        imageId: "a77bed0a24583af1e91932f40fdf1fc2",
        defaultPrice: 9900,
      },
      {
        id: "72240858",
        name: "Red Velvet Roll Cake Slice",
        category: "Ice Cream Cakes",
        imageId: "mn0kgib46u4vrudyqxjh",
        price: 12900,
      },
    ],
  },
  {
    id: "251589",
    name: "Euphoria",
    cloudinaryImageId: "if3oxttqnbedseg0cpbd",
    locality: "Paradise",
    areaName: "Paradise Cross Roads",
    costForTwo: "₹600 for two",
    cuisines: ["Desserts", "Bakery"],
    menuCards: [
      {
        id: "85370478",
        name: "Classic Chocolate Brownie (250 Gms, 6pcs)",
        category: "Brownies",
        imageId: "yraof5aspcj3eb1zk8nt",
        price: 33898,
      },
      {
        id: "85370467",
        name: "Classic Chocolate Brownies (500gm, 12pcs)",
        category: "Brownies",

        imageId: "yraof5aspcj3eb1zk8nt",

        price: 63555,
      },
    ],
  },
  {
    id: "9304",
    name: "Rayalaseema Ruchulu",
    cloudinaryImageId: "oqngjvi8wsc38wffxfa6",
    locality: "Lakdi-Ka-Pul",
    areaName: "Lakdi-Ka-Pul",
    costForTwo: "₹450 for two",
    cuisines: ["South Indian", "Biryani", "Rayalaseema", "North Indian"],
    menuCards: [
      {
        id: "565171",
        name: "Sri Kanya Chicken Biryani Fry Piece - Cbf",
        category: "Non-veg Biryani",
        imageId: "buchh1zmqz5ag5q13mmo",
        price: 31000,
      },
      {
        id: "565172",
        name: "Chicken Dum Biryani",
        category: "Non-veg Biryani",
        imageId: "lpgp50r2bjex7pqp94vz",
        price: 30000,
      },
    ],
  },
  {
    id: "153046",
    name: "Huber & Holly",
    cloudinaryImageId: "cujunjtk1tta0i8t9ffw",
    locality: "RAFSA TOWER",
    areaName: "Himayath Nagar",
    costForTwo: "₹500 for two",
    cuisines: ["Pizzas", "Beverages", "Ice Cream"],
    menuCards: [
      {
        id: "72241029",
        name: "Mississippi Mud Ice Cream",
        category: "Chocolate Ice Creams",
        imageId: "a77bed0a24583af1e91932f40fdf1fc2",
        defaultPrice: 9900,
      },
      {
        id: "72240858",
        name: "Red Velvet Roll Cake Slice",
        category: "Ice Cream Cakes",
        imageId: "mn0kgib46u4vrudyqxjh",
        price: 12900,
      },
    ],
  },
  {
    id: "24613",
    name: "Domino's Pizza",
    cloudinaryImageId: "hbeqc0r6ifvqiuychft2",
    locality: "Stock Exchange Road",
    areaName: "Himayath Nagar",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    menuCards: [
      {
        id: "117104750",
        name: "Blazing Onion & Paprika",
        category: "New Launches",

        imageId: "09829ae11e2534aeac210833c2f2ae39",

        defaultPrice: 32900,
      },
      {
        id: "117104751",
        name: "Fiery Jalapeno & Paprika",
        category: "New Launches",

        imageId: "0d542e845410d41657e1c91cd53704d1",

        defaultPrice: 32900,
      },
    ],
  },
  {
    id: "17104",
    name: "KFC",
    cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
    locality: "Prime Plaza",
    areaName: "Himayatnagar",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    menuCards: [
      {
        id: "108265691",
        name: "Chicken Chizza",
        category: "Chicken Chizza",

        imageId: "886c6bc1e25897bcb7ffc1170c923928",

        price: 31905,
      },
      {
        id: "127996643",
        name: "Chicken Chizza & Wings Meal",
        category: "Chicken Chizza",

        imageId: "120374790af673aae76c5a5d883d45ad",

        price: 45905,
      },
      {
        id: "108265689",
        name: "Duo-Chicken Chizza",
        category: "Chicken Chizza",

        price: 62857,
      },
    ],
  },
  {
    id: "16158",
    name: "Royal Tiffin Centre",
    cloudinaryImageId: "xxvnkzmpgmbojcakxws4",
    locality: "Hanuman Tekdi",
    areaName: "Abids & Koti",
    costForTwo: "₹150 for two",
    cuisines: ["South Indian"],
    menuCards: [
      {
        id: "2906575",
        name: "Upma",
        category: "Upma",
        description: "Serves 1",
        imageId: "msqlcjzuen5ivzlb55m5",

        price: 5000,
      },
      {
        id: "72063587",
        name: "Butter idly single",
        category: "Idly",
        description: "Serves 1",
        imageId: "d8ca5a8cc341a9a88725b10d5bbeb5fc",

        price: 4000,
      },
      {
        id: "72063593",
        name: "Pizza Idly",
        category: "Idly",
        description: "Serves 1",
        imageId: "g6lxlermchutqztm1aas",

        price: 19000,
      },
    ],
  },
  {
    id: "2796",
    name: "Blue Fox by Minerva Grand",
    cloudinaryImageId: "f4qom4lutrgkefkb5tmv",
    locality: "Himayath Nagar",
    areaName: "Himayatnagar",
    costForTwo: "₹800 for two",
    cuisines: ["Biryani", "North Indian", "Chinese", "Tandoor"],
    menuCards: [
      {
        id: "3747470",
        name: "Chicken Spring Roll",
        category: "Indian",

        imageId: "56c173e2572d6991b18e2379de95cfa8",

        price: 40000,
      },
      {
        id: "3747441",
        name: "Curd Rice",
        category: "Indian",

        imageId: "cwnsn68r2lfkyya6xiz7",

        price: 18000,
      },
    ],
  },
];
